ckeditor/ckeditor5-basic-styles

- src/bold.js
- src/italic.js
> Hidden the button labels

- src/bold.js
- src/italic.js
Fixes: https://github.com/ckeditor/ckeditor5/issues/211
Related to:
- https://github.com/ckeditor/ckeditor5-utils/pull/49
- https://github.com/ckeditor/ckeditor5-undo/pull/20
- https://github.com/ckeditor/ckeditor5-ui-default/pull/32
- https://github.com/ckeditor/ckeditor5-typing/pull/25
- https://github.com/ckeditor/ckeditor5-theme-lark/pull/22
- https://github.com/ckeditor/ckeditor5-engine/pull/530
- https://github.com/ckeditor/ckeditor5-delete/pull/13
> Changed const to lower case.

- src/bold.js
- src/italic.js
Fixes https://github.com/ckeditor/ckeditor5-ui-default/issues/30
Depends on https://github.com/ckeditor/ckeditor5-ui-default/pull/31
> Removed button parameter.

- tests/manual/basic-styles.js
Fixes: https://github.com/ckeditor/ckeditor5-typing/issues/17
Depends on: https://github.com/ckeditor/ckeditor5-typing/pull/24
> Fixed tests after package merged.

- src/boldengine.js
- src/italicengine.js
Fixes: https://github.com/ckeditor/ckeditor5-engine/issues/467
Depends on: https://github.com/ckeditor/ckeditor5-engine/pull/524
> Renamed converter builders

- src/bold.js
- src/boldengine.js
- src/italic.js
- src/italicengine.js
> Added docs to Bold and Italic features

- src/bold.js
- src/boldengine.js
- src/italic.js
- src/italicengine.js
- tests/bold.js
- tests/boldengine.js
- tests/italic.js
- tests/italicengine.js
> Changed paths and docs to use ckeditor5-core package

- src/bold.js
- src/italic.js
> t/14: Removed ui.button.ButtonModel#iconAlign attribute from Button models.

- .jshintrc
- tests/.jshintrc
- tests/bold.js
- tests/italic.js
- tests/manual/basic-styles.js
> Changed: turned JSHint browser setting to false.

- tests/boldengine.js
- tests/italicengine.js
Fixes https://github.com/ckeditor/ckeditor5-engine/issues/306
Depends on: https://github.com/ckeditor/ckeditor5-engine/pull/554
> Refactored model utils.

- tests/manual/basic-styles.html
> Fixed path to ckeditor.css

- tests/boldengine.js
- tests/italicengine.js
Missing cleanup after https://github.com/ckeditor/ckeditor5-engine/issues/455.
> Removed workaround in test.

- src/boldengine.js
- src/italicengine.js
- tests/boldengine.js
- tests/italicengine.js
Fixes: #24 
Depends on: https://github.com/ckeditor/ckeditor5-core/pull/10
> Renamed AttributeCommand class.

- src/bold.js
- src/italic.js
- tests/bold.js
- tests/italic.js
> Implemented tooltips with keystroke information next to Bold and Italic buttons

- src/bold.js
- src/italic.js
- tests/bold.js
- tests/italic.js
Closes #31.
Requires https://github.com/ckeditor/ckeditor5-ui/pull/100.
> Updated basic styles classes after the removal of Controller class.

- src/bold.js
- src/italic.js
- tests/bold.js
- tests/italic.js
> t/35: Cleaned up button attribute definitions.

- tests/attributecommand.js
Tests: Changes required by refactoring in ckeditor5-engine.
> Changes required by refactor in ckeditor5-engine.

- src/boldengine.js
- src/codeengine.js
- src/italicengine.js
- src/strikethroughengine.js
- src/underlineengine.js
Other: Aligning with new conversion helpers API.
---
*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*
>  Other: Aligning with new conversion helpers API

- src/italic/italicediting.js
Docs: Correct italic editing class description. Closes #88.
> Correct italic editing class description.

- docs/_snippets/features/basic-styles.js
- docs/_snippets/features/build-basic-styles-source.js
- package.json
Docs: Add remove formatting plugin to basic styles snippet. Closes #87.
> Add remove formatting plugin to basic styles snippet

- docs/features/basic-styles.md
Type: Message. Closes #000.
---
*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*
> Docs: Fix ckeditor5-basic-styles documentation

- src/bold/boldui.js
- src/code/codeui.js
- src/italic/italicui.js
- src/strikethrough/strikethroughui.js
- src/subscript/subscriptui.js
- src/superscript/superscriptui.js
- src/underline/underlineui.js
Fix: Focus the editor before executing toolbar buttons' command.
Master PR: https://github.com/ckeditor/ckeditor5/pull/6066
> i/353: Focus the editor before executing a command
